### ISSUE TITLE
Problems with evaporateOptions PropType definition

### ISSUE THREAD

**Issue by ururk** [kpantic/react-s3-uploader-multipart#4]
I'm getting this error:

`Warning: ReactClass: prop type `evaporateOptions` is invalid; it must be a function, usually from React.PropTypes.`

Looking at the definition for `evaporateOptions`, it is:

```js
        evaporateOptions: PropTypes.object.required,
```

However, this doesn't seem to work, the current documentation for prop-types indicates it should be:

```js
        evaporateOptions: PropTypes.object.isRequired,
```

**Comment by Djolivald** [comment]
Hey! I'm experiencing the same issue, can this get merged in ?

**Comment by Djolivald** [comment]
Hey @kpantic sorry to @ you but is it possible to get this PR along with https://github.com/kpantic/react-s3-uploader-multipart/pull/7 merged in? It'll fix the typos and make this lib usable! Thanks for the work ! ;)
